-- Create a table for recipe ratings
create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  recipe_id text not null, -- Assuming recipe_id corresponds to saved_recipes.id which is likely UUID or text
  user_id text not null,   -- Storing the user_id from the auth provider (Clerk/Supabase)
  rating integer not null check (rating >= 1 and rating <= 5),
  
  -- Add a constraint to ensure one rating per user per recipe
  unique(recipe_id, user_id)
);

-- Turn on RLS
alter table public.ratings enable row level security;

-- Allow users to read all ratings (needed for average calc if done client side, but here we do server side)
-- But generally good to allow read.
create policy "Enable read access for all users"
on public.ratings for select
using (true);

-- Allow authenticated users to insert/update their own ratings
create policy "Enable insert/update for authenticated users based on user_id"
on public.ratings for insert
with check (auth.uid()::text = user_id);

create policy "Enable update for users based on user_id"
on public.ratings for update
using (auth.uid()::text = user_id);



