import React from 'react';

const FAQ: React.FC = () => {
    return (
        <div className="w-full max-w-4xl mx-auto p-6 md:p-8 bg-white dark:bg-gray-800 rounded-2xl shadow-sm my-8 animate-fade-in text-amber-900 dark:text-gray-100">
            <h1 className="text-3xl font-bold font-serif mb-8 text-amber-900 dark:text-amber-500 text-center">Frequently Asked Questions</h1>

            <div className="space-y-6">

                <div className="border-b border-amber-100 dark:border-gray-700 pb-4">
                    <h3 className="text-xl font-semibold mb-2 text-amber-800 dark:text-amber-300">How does the AI recipe generation work?</h3>
                    <p className="text-gray-700 dark:text-gray-300">
                        We use advanced computer vision and language models (Google Gemini) to analyze your food photos. The AI identifies the dish and its ingredients, then generates a complete recipe with instructions, cooking times, and nutritional estimates.
                    </p>
                </div>

                <div className="border-b border-amber-100 dark:border-gray-700 pb-4">
                    <h3 className="text-xl font-semibold mb-2 text-amber-800 dark:text-amber-300">Is my data private?</h3>
                    <p className="text-gray-700 dark:text-gray-300">
                        Yes! We do not store the photos you upload for public viewing. They are processed securely solely to generate your recipe and then discarded. We value your privacy and security above all else.
                    </p>
                </div>

                <div className="border-b border-amber-100 dark:border-gray-700 pb-4">
                    <h3 className="text-xl font-semibold mb-2 text-amber-800 dark:text-amber-300">Can I save recipes?</h3>
                    <p className="text-gray-700 dark:text-gray-300">
                        Absolutely. If you sign in with your Google account, you can save any generated recipe to your personal "Saved Recipes" cookbook and access it anytime from any device.
                    </p>
                </div>

                <div className="border-b border-amber-100 dark:border-gray-700 pb-4">
                    <h3 className="text-xl font-semibold mb-2 text-amber-800 dark:text-amber-300">How do I manage dietary restrictions?</h3>
                    <p className="text-gray-700 dark:text-gray-300">
                        You can set your dietary preferences (like Vegetarian, Gluten-Free, Nut-Free) in your Profile settings. The AI will automatically try to adapt generated recipes to fit your needs.
                    </p>
                </div>

                <div className="pb-4">
                    <h3 className="text-xl font-semibold mb-2 text-amber-800 dark:text-amber-300">Is the nutritional information accurate?</h3>
                    <p className="text-gray-700 dark:text-gray-300">
                        The nutritional values provided are estimates generated by the AI based on standard ingredient data. They should be used as a guide only and not for strict medical or dietary monitoring.
                    </p>
                </div>

            </div>
        </div>
    );
};

export default FAQ;
