import React from 'react';

const Terms: React.FC = () => {
    return (
        <div className="w-full max-w-4xl mx-auto p-6 md:p-8 bg-white dark:bg-gray-800 rounded-2xl shadow-sm my-8 animate-fade-in text-amber-900 dark:text-gray-100">
            <h1 className="text-3xl font-bold font-serif mb-6 text-amber-900 dark:text-amber-500">Terms of Service</h1>

            <div className="prose dark:prose-invert max-w-none space-y-4">
                <p><strong>Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</strong></p>
                <p>
                    Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the Snap-a-Recipe application (the "Service") operated by us.
                </p>
                <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.</p>

                <h3 className="text-xl font-semibold mt-6 mb-2">1. User Content</h3>
                <p>
                    Our Service allows you to upload images ("User Content"). You retain any and all of your rights to any User Content you submit. By submitting User Content to the Service, you grant us the right and license to use this content solely for the purpose of generating a recipe for you.
                </p>

                <h3 className="text-xl font-semibold mt-6 mb-2">2. Prohibited Uses</h3>
                <p>You agree not to use the Service to upload or generate content that is unlawful, obscene, defamatory, or otherwise objectionable.</p>

                <h3 className="text-xl font-semibold mt-6 mb-2">3. Disclaimer</h3>
                <p>
                    The recipes provided by the Service are generated by an AI model and are for informational purposes only. We do not guarantee the accuracy, completeness, or safety of any recipe. You should always use your best judgment, follow safe food handling practices, and consult a professional if you have any dietary restrictions or health concerns.
                </p>

                <h3 className="text-xl font-semibold mt-6 mb-2">4. Termination</h3>
                <p>
                    We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
                </p>

                <h3 className="text-xl font-semibold mt-6 mb-2">5. Contact Us</h3>
                <p>If you have any questions about these Terms, please contact us at: [Your Contact Email Here]</p>
            </div>
        </div>
    );
};

export default Terms;
